// react/web/src/register/Register.tsx
import React, { Component, useEffect, useState } from 'react';
import MyService from '../service/Service';
import './Register.css'
import { InputText } from 'primereact/inputtext';
import { Calendar, CalendarChangeEvent } from 'primereact/calendar';
import { Button } from 'primereact/button';
import { useNavigate } from 'react-router-dom';





interface RegisterProps {
    size: string;
    level: string;
    service: MyService;
}

const Register: React.FC<RegisterProps> = ({ service, size, level }) => {

    const navigate = useNavigate()

    const [firstName, setfirstName] = useState('');
    const [lastname, setlastname] = useState('');
    const [username, setusername] = useState('');
    const [email, setemail] = useState('');
    const [date, setDate] = useState<string | Date | Date[] | null>(null);

    const [userNameExistst, setUserNameExists] = useState(false);
    const [isAdult, setIsAdult] = useState(false);
    const [firstNameExists, setFirstNameExists] = useState(false);
    const [lastNameExists, setLastNameExists] = useState(false);
    const [emailValid, setEmailValid] = useState(false);
    const [validated, setValidated] = useState(false);

    const emailRegex: RegExp = /^.*@hft.de$/;

    var ages = 0

    function checkAge(birth: any) {
        if (date != null) {
            console.log("age")
            var today = new Date();
            var age = today.getFullYear() - birth.getFullYear();
            var month = today.getMonth() - birth.getMonth();
            if (month < 0 || (month === 0 && today.getDate() < birth.getDate())) {
                age--;
            }
            if (age >= 18) {
                setIsAdult(true);
            } else
                setIsAdult(false);
            validate()
            ages = age
        }
    }

    function checkEmailValid(mail: string): void {
        setEmailValid(emailRegex.test(mail));
        validate();
    }

    function validate(): boolean {
        console.log("validating")
        if (firstNameExists && lastNameExists &&
            emailValid) {
            setValidated(true)
            return true;
        }
        return false;
    }

    function checkName(): void {
        if (firstName !== '') {
            setFirstNameExists(true);
        } else {
            setFirstNameExists(false);
        }
        if (lastname !== '') {
            setLastNameExists(true);
        } else {
            setLastNameExists(false);
        }
        if (username !== '') {
            setUserNameExists(true);
        } else {
            setUserNameExists(false);
        }
        validate();
    }

    useEffect(() => {
        document.title = 'Register A'
    })

    var menu = [{}]

    useEffect(() => {
        checkName()
        checkEmailValid(email)
        checkAge(date)
    }, [username, firstName, lastname, email, date]);

    return (
        <div lang='eng' title='register'>
            <h1>Register Level A</h1>
            <div className='center'>
                <div id='form'>
                    <div className='elemnt'>
                        <div className='labels' >
                            <label tabIndex={0} aria-label='firstname' className={`${size === 'size1' ? 'label' : size === 'size2' ? 'label-two' : 'label-half'}`}>Fistname:</label>

                            {!firstNameExists && <label tabIndex={0} className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`}>* field is required</label>}
                        </div>
                        <div className="col w-full">
                            <div className="card flex justify-content-center">
                                <InputText tabIndex={0} className={`${size === 'size1' ? 'p-input-one' : size === 'size2' ? 'p-input-two' : 'p-input-half'}`} role='name' aria-labelledby='input firstname' value={firstName} onChange={(e) => setfirstName(e.target.value)} />
                            </div>
                        </div>
                    </div>
                    <div className='elemnt'>
                        <div className='labels' >
                            <label tabIndex={0} aria-label='lastname' className={`${size === 'size1' ? 'label' : size === 'size2' ? 'label-two' : 'label-half'}`}>Lastname:</label>

                            {!lastNameExists && <label tabIndex={0} className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`}>* field is required</label>}
                        </div>
                        <div className="col w-full">
                            <div className="card flex justify-content-center">
                                <InputText tabIndex={0} className={`${size === 'size1' ? 'p-input-one' : size === 'size2' ? 'p-input-two' : 'p-input-half'}`} role='name' aria-labelledby='input firstname' value={lastname} onChange={(e) => setlastname(e.target.value)} />
                            </div>
                        </div>
                    </div>
                    <div className='elemnt'>
                        <div className='labels' >
                            <label tabIndex={0} aria-label='firstname' className={`${size === 'size1' ? 'label' : size === 'size2' ? 'label-two' : 'label-half'}`}>Username:</label>

                            {!userNameExistst && <label tabIndex={0} className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`}>* field is required</label>}
                        </div>
                        <div className="col w-full">
                            <div className="card flex justify-content-center">
                                <InputText tabIndex={0} className={`${size === 'size1' ? 'p-input-one' : size === 'size2' ? 'p-input-two' : 'p-input-half'}`} role='name' aria-labelledby='input firstname' value={username} onChange={(e) => { setusername(e.target.value); checkName() }} />
                            </div>
                        </div>
                    </div>

                    <div className='elemnt'>
                        <div className='labels' >
                            <label tabIndex={0} aria-label='firstname' className={`${size === 'size1' ? 'label' : size === 'size2' ? 'label-two' : 'label-half'}`}>Email:</label>

                            {!emailValid && <label tabIndex={0} className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`}>* field is required</label>}
                        </div>
                        <div className="col w-full">
                            <div className="card flex justify-content-center">
                                <InputText tabIndex={0} className={`${size === 'size1' ? 'p-input-one' : size === 'size2' ? 'p-input-two' : 'p-input-half'}`} role='name' aria-labelledby='input firstname' value={email} onChange={(e) => setemail(e.target.value)} />
                            </div>
                        </div>
                    </div>
                    <div className='elemnt'>
                        <div className='labels' >
                            <label tabIndex={0} aria-label='firstname' className={`${size === 'size1' ? 'label' : size === 'size2' ? 'label-two' : 'label-half'}`}>Birthday:</label>

                            {!isAdult && <label tabIndex={0} className={`${size === 'size1' ? 'error-required' : size === 'size2' ? 'error-required-two' : 'error-required-half'}`}>* field is required</label>}
                        </div>
                        <div className={`${size === 'size1' ? 'calendar-one' : size === 'size2' ? 'calendar-two' : 'calendar-half'}`}>
                            <div className="card flex justify-content-center">
                                <Calendar showIcon className="cal" value={date} onChange={(e: CalendarChangeEvent) => setDate(e.value as Date | null)} />
                            </div>
                        </div>
                    </div>
                    <div className='buttonContainer'>
                        <div className='left'>
                            <Button label='Submit' disabled={!validated}></Button>
                        </div>
                        <div className='right'>
                            <Button label='Cancel'></Button>
                        </div>
                    </div>
                </div>
            </div >
        </div >


    )
}

export default Register

// angular/web/src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { LocationService } from '../service/location.service';
import { Router } from '@angular/router';
import { DataService } from '../service/data.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css', "../../../src/styles.css"]
})
export class RegisterComponent implements OnInit {
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  birthday: Date;
  validated: boolean;
  isAdult: boolean;
  firstNameExists: boolean;
  lastNameExistst: boolean;
  userNameExistst: boolean;
  emailValid: boolean;
  size: string;

  readonly emailRegex: RegExp = /^.*@hft.de$/;

  constructor(private location: LocationService, private data: DataService, private router: Router) {
    this.firstName = '';
    this.lastName = '';
    this.username = '';
    this.email = '';
    this.validated = false;
  }
  ngOnInit(): void {
    this.data.currentMessage.subscribe(message => this.size = message);
    this.location.currentLocation = 'register';
  }

  validate(): boolean {
    if (this.firstNameExists && this.lastNameExistst &&
      this.emailValid && this.isAdult) {
      this.validated = true;
      return true;
    }
    return false;
  }

  checkEmailValid(mail: string): void {
    this.emailValid = this.emailRegex.test(mail);
    this.validate();
  }


  handleClick(link: string) {
    this.redirectToAnotherPage(link);
  }

  handleKeyDown(event: KeyboardEvent, link: string) {
    if (event.key === 'Enter') {
      this.redirectToAnotherPage(link);
    }
  }

  redirectToAnotherPage(link: string) {
    this.router.navigate(['/' + link]);
  }

  checkName(): void {
    if (this.firstName != '') {
      this.firstNameExists = true;
      console.log("first name exists: " + this.firstNameExists)
    } else {
      this.firstNameExists = false;
    }
    if (this.lastName != '') {
      this.lastNameExistst = true;
      console.log("lastname exists: " + this.lastNameExistst)
    } else {
      this.lastNameExistst = false;
    }
    if (this.username != '') {
      this.userNameExistst = true;
      console.log("lastname exists: " + this.userNameExistst)
    } else {
      this.userNameExistst = false;
    }
    this.validate()
  }

  checkAge(birth: Date): void {
    var today = new Date();
    var age = today.getFullYear() - birth.getFullYear();
    var month = today.getMonth() - birth.getMonth();
    if (month < 0 || (month === 0 && today.getDate() < birth.getDate())) {
      age--;
    }
    console.log("age: " + age)
    if (age >= 18) {
      this.isAdult = true;
    } else
      this.isAdult = false;
    this.validate()
  }

  onSubmit() {
    // Hier kannst du die Registrierungslogik implementieren
    // Zum Beispiel: Senden der Daten an einen Server
    console.log('Form submitted!');
    console.log('Vorname:', this.firstName);
    console.log('Nachname:', this.lastName);
    console.log('E-Mail:', this.email);
    console.log('Geburtstag:', this.birthday);
  }
}
<h1>Register Level A</h1>
<div class="center">
    <div [ngClass]="{'form-half' : size == 'size'}" class="p-fluid" id="form">
        <div class="col-2">
            <label for="firstName"
                [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">Fistname:</label>
            <label *ngIf="!firstNameExists"
                [ngClass]="{'error-required': size == 'size1', 'error-required-two' : size == 'size2', 'error-required-half' : size == 'size15' }">*
                field is required</label>
            <div class="col w-full">
                <input [attr.aria-required]="true" [attr.aria-invalid]="!firstNameExists" spellcheck="true"
                    [ngClass]="{'p-input-one' : size == 'size1', 'p-input-half' : size == 'size15', 'p-input-two' : size == 'size2'}"
                    (ngModelChange)="checkName()" id="firstName" aria-label="input firstName" pInputText type="text"
                    [(ngModel)]="firstName" />
            </div>
        </div>

        <div class="col-2">
            <label for="lastName"
                [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
                Lastname:</label>
            <label *ngIf="!lastNameExistst"
                [ngClass]="{'error-required': size == 'size1', 'error-required-two' : size == 'size2', 'error-required-half' : size == 'size15' }">*
                field is required</label>
            <div>
                <input [attr.aria-required]="true" [attr.aria-invalid]="!lastNameExistst"
                    [ngClass]="{'p-input-one' : size == 'size1', 'p-input-half' : size == 'size15', 'p-input-two' : size == 'size2'}"
                    (ngModelChange)="checkName()" id="lastName" aria-label="input lastName" pInputText type="text"
                    [(ngModel)]="lastName" />
            </div>
        </div>

        <div class="col-2">
            <label for="email"
                [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">E-Mail:</label>
            <label *ngIf="!email"
                [ngClass]="{'error-required': size == 'size1', 'error-required-two' : size == 'size2', 'error-required-half' : size == 'size15' }">*
                field is required </label>
            <div>
                <input [attr.aria-required]="true" [attr.aria-invalid]="!emailValid"
                    [ngClass]="{'p-input-one' : size == 'size1', 'p-input-half' : size == 'size15', 'p-input-two' : size == 'size2'}"
                    pInputText id="email" (change)="checkEmailValid(email)" aria-label="input email" pInputText
                    type="email" [(ngModel)]="email" />
            </div>
        </div>

        <div class="col-2">
            <label for="email"
                [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">Username:</label>
            <label *ngIf="!userNameExistst"
                [ngClass]="{'error-required': size == 'size1', 'error-required-two' : size == 'size2', 'error-required-half' : size == 'size15' }">*
                field is required</label>
            <div>
                <input [attr.aria-required]="true" [attr.aria-invalid]="!userNameExistst"
                    [ngClass]="{'p-input-one' : size == 'size1', 'p-input-half' : size == 'size15', 'p-input-two' : size == 'size2'}"
                    (ngModelChange)="checkName()" id="username" aria-label="input username" pInputText type="username"
                    [(ngModel)]="username" />
            </div>
        </div>

        <div class="col-2" tabindex="-1">
            <label for="birthday"
                [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">Birthday:</label>
            <label *ngIf="!isAdult"
                [ngClass]="{'error-required': size == 'size1', 'error-required-two' : size == 'size2', 'error-required-half' : size == 'size15' }">*
                field is required</label>
            <div>
                <p-calendar [attr.aria-required]="true" [attr.aria-invalid]="!isAdult"
                    [ngClass]="{'calendar-one': size === 'size1', 'calendar-half': size === 'size15', 'calendar-two': size === 'size2'}"
                    (onSelect)="checkAge(birthday)" aria-label="input birthday" name="date" [(ngModel)]="birthday"
                    [showIcon]="true"></p-calendar>
            </div>
        </div>

        <div class="buttoncontainer">
            <div class="left">
                <p-button
                    [ngClass]="{'button-one' : size == 'size1', 'button-half' : size == 'size15', 'button-two' : size == 'size2', }"
                    pRipple aria-label="submit register form" [disabled]="!validated" label="Submit"></p-button>
            </div>
            <div class="right">
                <a href="/"><p-button
                        [ngClass]="{'button-one' : size == 'size1', 'button-half' : size == 'size15', 'button-two' : size == 'size2', }"
                        router-l aria-label="cancel register form" label="Cancel"></p-button>
                </a>
            </div>
        </div>
    </div>
</div>
