// angular/web/src/app/app.component.ts
import { Component, OnInit, ChangeDetectorRef, NgZone, AfterViewInit, ChangeDetectionStrategy } from '@angular/core';
import { MenuItem } from "primeng/api";
import { DataService } from './service/data.service';
import { LocationService } from './service/location.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  changeDetection: ChangeDetectionStrategy.Default,
})
export class AppComponent implements OnInit, AfterViewInit {


  ngOnInit(): void {
    this.data.currentMessage.subscribe(message => this.size = message)
    this.data.currentLevel.subscribe(level => this.level = level)
    this.data.currentForeground.subscribe(color => this.foreground = color);
    this.data.currenBackground.subscribe(color => this.background = color);
    this.location.currentBc.subscribe(bc => {
      this.menuItems = bc;
    })
  }


  constructor(private data: DataService, private location: LocationService, private changeDetectorRef: ChangeDetectorRef) {
  }

  ngAfterViewInit(): void {
    this.location.currentBc.subscribe(bc => {
      this.menuItems = bc;
    })
  }

  title = 'Accessibility possibility of implementation';
  menuItems: MenuItem[];

  isExpanded: boolean = false;
  isSize: boolean = false;
  size: string = "size2";
  foreground: string = "#000000";
  background: string = "#ffffff";
  level: string;

  path: string = '';
  isRegister = this.location.isRegister;

  size1: boolean = true;
  size150: boolean = false;
  size200: boolean = false;


  items: MenuItem[] = [
    { label: 'Level A', tabindex: "1", target: "_self" },
    { label: 'Level AA', tabindex: "1", target: "_self" },
    { label: 'Level AAA', tabindex: "1", target: "_self" },
    { separator: true },
    { label: 'Font size up 50%', command: () => this.upSize(), tabindex: "1" },
    { label: 'Font size down 50%', command: () => this.downSize(), tabindex: "1" },

  ]

  getCurrentLocation(): void {
    this.items[0].url = this.location.currentLocation + '/A';
    this.items[1].url = this.location.currentLocation + '/AA';
    this.items[2].url = this.location.currentLocation + '/AAA';
  }

  changeForeground(): void {
    this.data.changeForegorund(this.foreground);
  }

  changeBackground(): void {
    this.data.changeBackgorund(this.background);
  }

  upSize() {
    if (this.size == "size1") {
      this.data.changeMessage("size15");
      return
    }
    if (this.size == "size15") {
      this.data.changeMessage("size2");
      return
    }
    if (this.size == "size2") {
      this.data.changeMessage("size2");
      return
    }
  }

  downSize() {
    if (this.size == "size1") {
      this.data.changeMessage("size1");
      return
    }
    if (this.size == "size15") {
      this.data.changeMessage("size1");
      return
    }
    if (this.size == "size2") {
      this.data.changeMessage("size15");
      return
    }
  }

  expandLinks() {
    this.isExpanded = true;
  }

  collapseLinks() {
    this.isExpanded = false;
  }

  toggleLinks() {
    this.isExpanded = !this.isExpanded;
  }

  expandSize() {
    this.isSize = true;
  }

  collapseSize() {
    this.isSize = false;
  }

  toggleSize() {
    this.isSize = !this.isSize;
  }



}

<header>
    <h2>Accessibility Test</h2>
    <nav class="navbar">
        <ul class="navLinks">
            <li><a routerLink="/main/AA" tabindex="0" target="_self">Home</a></li>
            <li><a routerLink="/register/A" tabindex="0" target="_self">About</a></li>
            <li><a href="#" tabindex="0" target="_self">Contact</a></li>
        </ul>
    </nav>
    <div class="abutton">
        <p-toast tabindex="1"></p-toast>
        <p-menu aria-label="Accessibility menu" (onShow)="getCurrentLocation()" #menu [model]="items" [popup]="true"
            tabindex="0"></p-menu>
        <button pButton type="button" (click)="menu.toggle($event)" icon="pi pi-bars" tabindex="0" label="A11y Menu"
            aria-label="Accessibility menu button"></button>
        <div *ngIf="level == 'AAA'" class="colorPickerDiv" [style]="{'padding-top': '5px'}">
            <p-colorPicker aria-label="choose foreground color" class="colorPicker" [(ngModel)]="foreground"
                (onChange)="changeForeground()"></p-colorPicker>
            <p-colorPicker aria-label="choose background color" [(ngModel)]="background"
                (onChange)="changeBackground()"></p-colorPicker>
        </div>
    </div>
</header>
<div class="bread">
    <div *ngIf="level == 'AAA'">
        <a>
            <i alt="home" class="pi pi-home"></i>
        </a>
        <a *ngFor="let b of menuItems" [href]="b.url">{{ b.label }}</a>
    </div>
</div>

<div class="container-fluid">
    <main role="main" class="">
        <router-outlet></router-outlet>
    </main>
</div>

// react/web/src/App.tsx
import React, { useState, useEffect, useRef } from 'react';
import logo from './logo.svg';
import './App.css';
import { Menu } from 'primereact/menu';
import { Toast } from 'primereact/toast';
import { Button } from 'primereact/button';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import Main from './main/Main';
import MainAA from './mainAA/MainAA';
import MainAAA from './mainAAA/MainAAA';
import MyService from './service/Service';
import { ColorPicker } from 'primereact/colorpicker';
import Register from './register/Register';


const myService = new MyService();

const App: React.FC = () => {


  const toast = useRef(null);
  const menuLeft = useRef<Menu>(null!);

  const [currentSize, setCurrentSize] = useState<string>("size1");
  const [currentLevel, setCurrentLevel] = useState<string>('');
  var [currentForeground, setCurrentForegorund] = useState<string>('#000000')
  var [currentBackground, setCurrentBackground] = useState<string>('#ffffff')

  useEffect(() => {
    const sizeSubscription = myService.getCurrentSize().subscribe((size) => {
      setCurrentSize(size);
    });


    const levelSubscription = myService.getCurrentLevel().subscribe((level) => {
      setCurrentLevel(level);
    });

    const foregorundSubscription = myService.getCurrentForegorund().subscribe((foreground) => {
      setCurrentForegorund(foreground);
    });

    const backgroundSubscription = myService.getCurrentBackgroundSubject().subscribe((background) => {
      setCurrentBackground(background);
    });

    // Clean up subscriptions when component unmounts
    return () => {
      sizeSubscription.unsubscribe();
      levelSubscription.unsubscribe();
      foregorundSubscription.unsubscribe();
      backgroundSubscription.unsubscribe();
    };
  }, []);

  var items = [
    { label: 'Level A', tabindex: "2", target: "_self" },
    { label: 'Level AA', tabindex: "2", target: "_self" },
    { label: 'Level AAA', tabindex: "8", target: "_self" },
    { separator: true, url: '' },
    { label: 'Font size up 50%', command: () => upSize(), tabindex: "9" },
    { label: 'Font size down 50%', command: () => downSize(), tabindex: "10" },
  ]



  const upSize = () => {
    if (currentSize == "size1") {
      setCurrentSize("size15");
      console.log(currentSize);
      return
    }
    if (currentSize == "size15") {
      setCurrentSize("size2");
      console.log(currentSize);
      return
    }
    if (currentSize == "size2") {
      setCurrentSize("size2");
      console.log(currentSize);
      return
    }
    console.log("noting")
  }

  const downSize = () => {
    if (currentSize == "size1") {
      setCurrentSize("size1");
      console.log(currentSize);
      return
    }
    if (currentSize == "size15") {
      setCurrentSize("size1");
      console.log(currentSize);
      return
    }
    if (currentSize == "size2") {
      setCurrentSize("size15");
      console.log(currentSize);
      return
    }
  }

  function getCurrentLocation(): void {
    items[0].url = myService.currentLocation + '/A';
    items[1].url = myService.currentLocation + '/AA';
    items[2].url = myService.currentLocation + '/AAA';
  }

  return (
    <div className="App">
      <header>
        <h2>Accessibility Test</h2>
        <nav className="navbar">
          <ul className="navLinks">
            <li><a href="" tabIndex={1} target="_self">Home</a></li>
            <li><a href="/register/A" tabIndex={1} target="_self">About</a></li>
            <li><a href="#" tabIndex={1} target="_self">Contact</a></li>
          </ul>
        </nav>
        <div className='abutton'>
          <Menu model={items} onShow={() => getCurrentLocation()} popup ref={menuLeft} id="popup_menu_left" tabIndex={2} appendTo={'self'} />
          <Button label="a11y menu" icon="pi pi-align-left" className="mr-2" tabIndex={1}
            onClick={(event) => menuLeft.current.toggle(event)} aria-controls="popup_menu_left" aria-haspopup />
          {currentLevel === 'AAA' && <div className='colorPickerDiv' style={{ paddingTop: '5px' }}>
            <ColorPicker inputId="cp-hex" format="hex" value={currentForeground} onChange={(e) => { setCurrentForegorund('#' + String(e.value)) }} className="mb-3" />
            <ColorPicker inputId="cp-hex" format="hex" className="mb-3" value={currentBackground} onChange={(e) => { setCurrentBackground('#' + String(e.value)) }} />
          </div>}
        </div >
      </header >
      <div tabIndex={3}>
        <BrowserRouter>
          <Routes>
            <Route path='*' element={<Navigate to="/main/A" replace={true} />} />
            <Route path='/main/A' element={<Main service={myService} size={currentSize} level={currentLevel} />} />
            <Route path='/main/AA' element={<MainAA service={myService} size={currentSize} level={currentLevel} />} />
            <Route path='/main/AAA' element={<MainAAA foreground={currentForeground} background={currentBackground} service={myService} size={currentSize} level={currentLevel} />} />
            <Route path='/register/A' element={<Register level={currentLevel} service={myService} size={currentSize} />} />
          </Routes>
        </BrowserRouter>
      </div>
    </div >
  );
}

export default App;
